### ISSUE TITLE
repo name suggestion for consistancy

### ISSUE THREAD

**Issue by hannesdelbeke** [ArtellaPipe/artellapipe-libs-pyblish#2]
to stay consistent with other pyblish repos, may i suggest to rename the repo and package to start with "pyblish-"

plottwist-libs-pyblish 
artellapipe-libs-pyblish

pyblish-lite
pyblish-photoshop
pyblish-3dsmax
pyblish-qml
pyblish-base
pyblish-houdini
pyblish-maya
pyblish
pyblish-nuke
pyblish-starter
pyblish-modo

**Comment by tpoveda** [comment]
It makes complete sense. Repo renamed to follow pyblish standards. Closing ticket. Thank you!
